### ISSUE TITLE
run test.py error

### ISSUE THREAD

**Issue by YatSenMeng** [Dmmm1997/DenseUAV#4]
hi, i'm run:
python3 test.py --test_dir ./datasets/DenseUAV/test
get:
We use the scale: 1
-------test-----------
Traceback (most recent call last):
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc749e06ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/vit_small_patch16_224.augreg_in21k_ft_in1k/resolve/main/pytorch_model.bin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc749e06ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 392, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 68, in send
    return super().send(request, *args, **kwargs)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/vit_small_patch16_224.augreg_in21k_ft_in1k/resolve/main/pytorch_model.bin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc749e06ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 86bb996b-c460-44cf-ace1-92030e969acc)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/my/workflow2024/01_project/DenseUAV/test.py", line 178, in <module>
    model = load_network(opt)
  File "/home/my/workflow2024/01_project/DenseUAV/tool/utils.py", line 146, in load_network
    model = make_model(opt)
  File "/home/my/workflow2024/01_project/DenseUAV/models/taskflow.py", line 39, in make_model
    model = Model(opt)
  File "/home/my/workflow2024/01_project/DenseUAV/models/taskflow.py", line 11, in __init__
    self.backbone = make_backbone(opt)
  File "/home/my/workflow2024/01_project/DenseUAV/models/Backbone/backbone.py", line 8, in make_backbone
    backbone_model = Backbone(opt)
  File "/home/my/workflow2024/01_project/DenseUAV/models/Backbone/backbone.py", line 17, in __init__
    self.backbone,self.output_channel = self.init_backbone(opt.backbone)
  File "/home/my/workflow2024/01_project/DenseUAV/models/Backbone/backbone.py", line 31, in init_backbone
    backbone_model = timm.create_model("vit_small_patch16_224", pretrained=True, img_size=self.img_size)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/timm/models/_factory.py", line 117, in create_model
    model = create_fn(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 1832, in vit_small_patch16_224
    model = _create_vision_transformer('vit_small_patch16_224', pretrained=pretrained, **dict(model_args, **kwargs))
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 1781, in _create_vision_transformer
    return build_model_with_cfg(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/timm/models/_builder.py", line 410, in build_model_with_cfg
    load_pretrained(
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/timm/models/_builder.py", line 190, in load_pretrained
    state_dict = load_state_dict_from_hf(pretrained_loc)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/timm/models/_hub.py", line 188, in load_state_dict_from_hf
    cached_file = hf_hub_download(hf_model_id, filename=filename, revision=hf_revision)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/my/.conda/envs/DenseUAV/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1406, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

It seem like network to download smoe pytorch model connenct error? Should i resovle this problem?

**Comment by Dmmm1997** [comment]
This is an error that you cannot download the weight from Hugging Face. Currently, HF is not supported by all countries. Maybe you can use the mirror of HF, or download the weight manually and change the code to specify the weight path. Or maybe you can refer to this link: https://zhuanlan.zhihu.com/p/676420788
